### ISSUE TITLE
This code is not supported by bigchaindb 2.0

### ISSUE THREAD

**Issue by arsen3d** [bigchaindb/project-jannowitz#2]
<img width="450" alt="screenshot 2018-05-31 10 02 00" src="https://user-images.githubusercontent.com/298235/40796349-aee2d1bc-64b9-11e8-88c8-b12647825cf8.png">
<img width="553" alt="screenshot 2018-05-31 10 02 48" src="https://user-images.githubusercontent.com/298235/40796414-d5263ada-64b9-11e8-8636-3b0d2c3e1077.png">
<img width="903" alt="screenshot 2018-05-31 10 04 27" src="https://user-images.githubusercontent.com/298235/40796496-18faaffc-64ba-11e8-852c-69bffea9cf44.png">

**Comment by gautamdhameja** [comment]
All code is now updated to run with BigchainDB 2.0
